### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by aquynh** [SuppenGeist/erebus#1]
this looks like a great project, but is there more docs/user manual?

keep it up, cheers.

**Comment by SuppenGeist** [comment]
As you may have seen i just started a week ago and right now im just trying to figure out what works and what doesnt. So there  wont be any usefule documentation anytime soon. But if you want to read up on how to make the plugins work (which is like 90% of the code right now) you can look at [this](http://www.drdobbs.com/cpp/building-your-own-plugin-framework-part/204202899?cid=RSSfeed%255FDDJ%255FCpp) tutorial.

**Comment by aquynh** [comment]
please inform when this is ready, we can link to your project from our website: http://www.capstone-engine.org/showcase.html
